// Language Data
const languages = [
  { code: 'en', name: 'English' },
  { code: 'es', name: 'Spanish (Español)' },
  { code: 'fr', name: 'French (Français)' },
  { code: 'de', name: 'German (Deutsch)' },
  { code: 'it', name: 'Italian (Italiano)' },
  { code: 'pt', name: 'Portuguese (Português)' },
  { code: 'ru', name: 'Russian (Русский)' },
  { code: 'ja', name: 'Japanese (日本語)' },
  { code: 'ko', name: 'Korean (한국어)' },
  { code: 'zh', name: 'Chinese (中文)' },
  { code: 'ar', name: 'Arabic (العربية)' },
  { code: 'hi', name: 'Hindi (हिन्दी)' },
  { code: 'bn', name: 'Bengali (বাংলা)' },
  { code: 'ur', name: 'Urdu (اردو)' },
  { code: 'tr', name: 'Turkish (Türkçe)' },
  { code: 'vi', name: 'Vietnamese (Tiếng Việt)' },
  { code: 'th', name: 'Thai (ไทย)' },
  { code: 'nl', name: 'Dutch (Nederlands)' },
  { code: 'pl', name: 'Polish (Polski)' },
  { code: 'sv', name: 'Swedish (Svenska)' },
  { code: 'da', name: 'Danish (Dansk)' },
  { code: 'no', name: 'Norwegian (Norsk)' },
  { code: 'fi', name: 'Finnish (Suomi)' },
  { code: 'el', name: 'Greek (Ελληνικά)' },
  { code: 'he', name: 'Hebrew (עברית)' },
  { code: 'id', name: 'Indonesian (Bahasa Indonesia)' },
  { code: 'ms', name: 'Malay (Bahasa Melayu)' },
  { code: 'tl', name: 'Filipino (Tagalog)' },
  { code: 'cs', name: 'Czech (Čeština)' },
  { code: 'ro', name: 'Romanian (Română)' },
  { code: 'hu', name: 'Hungarian (Magyar)' },
  { code: 'uk', name: 'Ukrainian (Українська)' }
];

// Country Data with SEO info and language associations
const countries = [
  { code: 'US', name: 'United States', region: 'North America', languages: ['en'] },
  { code: 'GB', name: 'United Kingdom', region: 'Europe', languages: ['en'] },
  { code: 'CA', name: 'Canada', region: 'North America', languages: ['en', 'fr'] },
  { code: 'AU', name: 'Australia', region: 'Oceania', languages: ['en'] },
  { code: 'DE', name: 'Germany', region: 'Europe', languages: ['de'] },
  { code: 'FR', name: 'France', region: 'Europe', languages: ['fr'] },
  { code: 'ES', name: 'Spain', region: 'Europe', languages: ['es'] },
  { code: 'IT', name: 'Italy', region: 'Europe', languages: ['it'] },
  { code: 'NL', name: 'Netherlands', region: 'Europe', languages: ['nl'] },
  { code: 'BE', name: 'Belgium', region: 'Europe', languages: ['nl', 'fr', 'de'] },
  { code: 'CH', name: 'Switzerland', region: 'Europe', languages: ['de', 'fr', 'it'] },
  { code: 'AT', name: 'Austria', region: 'Europe', languages: ['de'] },
  { code: 'SE', name: 'Sweden', region: 'Europe', languages: ['sv'] },
  { code: 'NO', name: 'Norway', region: 'Europe', languages: ['no'] },
  { code: 'DK', name: 'Denmark', region: 'Europe', languages: ['da'] },
  { code: 'FI', name: 'Finland', region: 'Europe', languages: ['fi', 'sv'] },
  { code: 'PL', name: 'Poland', region: 'Europe', languages: ['pl'] },
  { code: 'PT', name: 'Portugal', region: 'Europe', languages: ['pt'] },
  { code: 'IE', name: 'Ireland', region: 'Europe', languages: ['en'] },
  { code: 'NZ', name: 'New Zealand', region: 'Oceania', languages: ['en'] },
  { code: 'JP', name: 'Japan', region: 'Asia', languages: ['ja'] },
  { code: 'KR', name: 'South Korea', region: 'Asia', languages: ['ko'] },
  { code: 'CN', name: 'China', region: 'Asia', languages: ['zh'] },
  { code: 'IN', name: 'India', region: 'Asia', languages: ['hi', 'en', 'bn'] },
  { code: 'SG', name: 'Singapore', region: 'Asia', languages: ['en', 'zh', 'ms'] },
  { code: 'MY', name: 'Malaysia', region: 'Asia', languages: ['ms', 'en', 'zh'] },
  { code: 'TH', name: 'Thailand', region: 'Asia', languages: ['th'] },
  { code: 'PH', name: 'Philippines', region: 'Asia', languages: ['tl', 'en'] },
  { code: 'ID', name: 'Indonesia', region: 'Asia', languages: ['id'] },
  { code: 'VN', name: 'Vietnam', region: 'Asia', languages: ['vi'] },
  { code: 'BR', name: 'Brazil', region: 'South America', languages: ['pt'] },
  { code: 'MX', name: 'Mexico', region: 'North America', languages: ['es'] },
  { code: 'AR', name: 'Argentina', region: 'South America', languages: ['es'] },
  { code: 'CL', name: 'Chile', region: 'South America', languages: ['es'] },
  { code: 'CO', name: 'Colombia', region: 'South America', languages: ['es'] },
  { code: 'PE', name: 'Peru', region: 'South America', languages: ['es'] },
  { code: 'VE', name: 'Venezuela', region: 'South America', languages: ['es'] },
  { code: 'EC', name: 'Ecuador', region: 'South America', languages: ['es'] },
  { code: 'BO', name: 'Bolivia', region: 'South America', languages: ['es'] },
  { code: 'PY', name: 'Paraguay', region: 'South America', languages: ['es'] },
  { code: 'UY', name: 'Uruguay', region: 'South America', languages: ['es'] },
  { code: 'CR', name: 'Costa Rica', region: 'Central America', languages: ['es'] },
  { code: 'PA', name: 'Panama', region: 'Central America', languages: ['es'] },
  { code: 'GT', name: 'Guatemala', region: 'Central America', languages: ['es'] },
  { code: 'CU', name: 'Cuba', region: 'Caribbean', languages: ['es'] },
  { code: 'DO', name: 'Dominican Republic', region: 'Caribbean', languages: ['es'] },
  { code: 'PR', name: 'Puerto Rico', region: 'Caribbean', languages: ['es', 'en'] },
  { code: 'AE', name: 'UAE', region: 'Middle East', languages: ['ar', 'en'] },
  { code: 'SA', name: 'Saudi Arabia', region: 'Middle East', languages: ['ar'] },
  { code: 'IL', name: 'Israel', region: 'Middle East', languages: ['he', 'ar'] },
  { code: 'TR', name: 'Turkey', region: 'Middle East', languages: ['tr'] },
  { code: 'EG', name: 'Egypt', region: 'Africa', languages: ['ar'] },
  { code: 'MA', name: 'Morocco', region: 'Africa', languages: ['ar', 'fr'] },
  { code: 'DZ', name: 'Algeria', region: 'Africa', languages: ['ar', 'fr'] },
  { code: 'TN', name: 'Tunisia', region: 'Africa', languages: ['ar', 'fr'] },
  { code: 'JO', name: 'Jordan', region: 'Middle East', languages: ['ar'] },
  { code: 'LB', name: 'Lebanon', region: 'Middle East', languages: ['ar', 'fr'] },
  { code: 'KW', name: 'Kuwait', region: 'Middle East', languages: ['ar'] },
  { code: 'QA', name: 'Qatar', region: 'Middle East', languages: ['ar', 'en'] },
  { code: 'BH', name: 'Bahrain', region: 'Middle East', languages: ['ar'] },
  { code: 'OM', name: 'Oman', region: 'Middle East', languages: ['ar'] },
  { code: 'ZA', name: 'South Africa', region: 'Africa', languages: ['en'] },
  { code: 'NG', name: 'Nigeria', region: 'Africa', languages: ['en'] },
  { code: 'KE', name: 'Kenya', region: 'Africa', languages: ['en'] },
  { code: 'GH', name: 'Ghana', region: 'Africa', languages: ['en'] },
  { code: 'RU', name: 'Russia', region: 'Europe', languages: ['ru'] },
  { code: 'UA', name: 'Ukraine', region: 'Europe', languages: ['uk', 'ru'] },
  { code: 'BY', name: 'Belarus', region: 'Europe', languages: ['ru'] },
  { code: 'KZ', name: 'Kazakhstan', region: 'Asia', languages: ['ru'] },
  { code: 'PK', name: 'Pakistan', region: 'Asia', languages: ['ur', 'en'] },
  { code: 'BD', name: 'Bangladesh', region: 'Asia', languages: ['bn'] },
  { code: 'GR', name: 'Greece', region: 'Europe', languages: ['el'] },
  { code: 'CY', name: 'Cyprus', region: 'Europe', languages: ['el', 'tr'] },
  { code: 'CZ', name: 'Czech Republic', region: 'Europe', languages: ['cs'] },
  { code: 'SK', name: 'Slovakia', region: 'Europe', languages: ['cs'] },
  { code: 'RO', name: 'Romania', region: 'Europe', languages: ['ro'] },
  { code: 'MD', name: 'Moldova', region: 'Europe', languages: ['ro', 'ru'] },
  { code: 'HU', name: 'Hungary', region: 'Europe', languages: ['hu'] },
  { code: 'TW', name: 'Taiwan', region: 'Asia', languages: ['zh'] },
  { code: 'HK', name: 'Hong Kong', region: 'Asia', languages: ['zh', 'en'] }
];

// Theme Pages Configuration
const themePages = {
  blog: ['Home', 'About Us', 'Blog', 'Contact Us', 'Privacy Policy', 'Author Page'],
  business: ['Home', 'About Us', 'Services', 'Our Team', 'Testimonials', 'Contact Us', 'Privacy Policy'],
  service: ['Home', 'About Us', 'Services', 'How It Works', 'Pricing', 'FAQ', 'Contact Us', 'Privacy Policy'],
  ecommerce: ['Home', 'Products', 'Categories', 'About Us', 'Contact Us', 'Shipping Info', 'Return Policy', 'Privacy Policy'],
  portfolio: ['Home', 'About Me', 'Portfolio', 'Services', 'Testimonials', 'Contact', 'Privacy Policy'],
  landing: ['Home (Landing)', 'Features', 'Pricing', 'FAQ', 'Contact', 'Privacy Policy']
};
